# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest, macos-latest]
        include:
          # only run benchmarks for the following configuration...
          - os: ubuntu-latest
            python-version: 3.12
            benchmark: true

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PostgreSQL
      if: ${{ runner.os == 'macOS' }}
      run: brew install postgresql
    - name: Install Python package
      run: pip install -e . --group test
    - name: Test with pytest
      env:
        BENCHMARK: ${{ matrix.benchmark }}
        SQLALCHEMY_WARN_20: 1
      run: |
        PYTESTARGS="--cov --cov-report=xml"
        if [[ -z "${BENCHMARK}" ]]; then
          PYTESTARGS="${PYTESTARGS} --benchmark-skip"
        else
          PYTESTARGS="${PYTESTARGS} --benchmark-group-by=fullfunc --benchmark-sort=fullname --benchmark-json benchmark_results.json"
        fi
        pytest ${PYTESTARGS}
    # - name: Create runtime plots
    #   if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'}}
    #   run: |
    #     mkdir plots
    #     python .github/workflows/runtime_plots.py
    # - name: Upload plots to github artifacts
    #   if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'}}
    #   uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
    #   with:
    #     name: runtime-plots
    #     path: plots
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload benchmark results to github artifacts
      if: ${{ matrix.benchmark }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
      with:
        name: benchmark-results-json
        path: benchmark_results.json
